version: 2

workflows:
  version: 2
  test:
    jobs:
      - lint


default_image: &default_image
  docker:
    - image:  circleci/golang:1-stretch

jobs:
  lint:
    <<: *default_image
    steps:
      - checkout
      - restore_cache:
          keys:
            - mod-cache-{{ checksum "go.sum" }}
            - mod-cache-
      - run: go mod vendor
      - run:
           name: install go packages for CI
           command: |
             go install golang.org/x/lint/golint \
                        github.com/haya14busa/reviewdog/cmd/reviewdog \
                        github.com/golangci/golangci-lint/cmd/golangci-lint
      - save_cache:
          key: mod-cache-{{ checksum "go.sum" }}
          paths:
            - vendor
      - run: RESULT=$(gofmt -d -s ./cmd/ ./test/) && echo "${RESULT}"; ! [ -n "${RESULT}" ]
      - run:
          name: run reviewdog
          command: bin/ci/reviewdog.sh -reporter=github-pr-review
